import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import MapboxExample from "@/components/testmap";
import MapWithGeocoder from "@/components/geoCoder";
import MapWithLines from "@/components/mapLocations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: "100vh",width: "100vw",display: "flex" }}>
        {/* <MapboxExample/> */}
        {/* <MapWithGeocoder/> */}
        <MapWithLines/>
      </div>
    </>
  );
}
